name: main
on:
  push:
    tags: '*'
jobs:
  main:
    runs-on: windows-2019
    steps:
    - name: install aqt
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%
        where aqt || pip install aqtinstall
    - name: test env
      shell: cmd
      run: |
        where curl || exit /b
        where 7z || exit /b
    - name: flavour qwt6.2.0 qt5.15.2 mingw8.1.0 i686
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;%CD%\5.15.2\mingw81_32\bin;%CD%\Tools\mingw810_32\bin;%PATH%
        where aqt || exit /b
        if not exist Tools\mingw810_32\bin\gcc.exe aqt install-tool windows desktop tools_mingw qt.tools.win32_mingw810
        if not exist 5.15.2\mingw81_32\bin\qmake.exe aqt install-qt windows desktop 5.15.2 win32_mingw81
        if not exist "qwt-6.2.0.zip" curl -L -o qwt-6.2.0.zip "https://altushost-swe.dl.sourceforge.net/project/qwt/qwt/6.2.0/qwt-6.2.0.zip"
        if exist qwt-6.2.0 rmdir /q /s qwt-6.2.0
        7z x -y "qwt-6.2.0.zip"
        where qmake || exit /b
        where gcc || exit /b
        pushd qwt-6.2.0
        qmake
        mingw32-make
        mingw32-make install
        popd
        7z a "qwt6.2.0-qt5.15.2-mingw8.1.0-i686.zip" "C:\Qwt-6.2.0"
        if exist C:\Qwt-6.2.0 rmdir /q /s C:\Qwt-6.2.0
    - name: flavour qwt6.2.0 qt5.15.2 mingw8.1.0 x86_64
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;%CD%\5.15.2\mingw81_64\bin;%CD%\Tools\mingw810_64\bin;%PATH%
        where aqt || exit /b
        if not exist Tools\mingw810_64\bin\gcc.exe aqt install-tool windows desktop tools_mingw qt.tools.win64_mingw810
        if not exist 5.15.2\mingw81_64\bin\qmake.exe aqt install-qt windows desktop 5.15.2 win64_mingw81
        if not exist "qwt-6.2.0.zip" curl -L -o qwt-6.2.0.zip "https://altushost-swe.dl.sourceforge.net/project/qwt/qwt/6.2.0/qwt-6.2.0.zip"
        if exist qwt-6.2.0 rmdir /q /s qwt-6.2.0
        7z x -y "qwt-6.2.0.zip"
        where qmake || exit /b
        where gcc || exit /b
        pushd qwt-6.2.0
        qmake
        mingw32-make
        mingw32-make install
        popd
        7z a "qwt6.2.0-qt5.15.2-mingw8.1.0-x86_64.zip" "C:\Qwt-6.2.0"
        if exist C:\Qwt-6.2.0 rmdir /q /s C:\Qwt-6.2.0
    - name: flavour qwt6.2.0 qt5.15.2 msvc2019 i686
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;%CD%\5.15.2\msvc2019\bin;%PATH%
        where aqt || exit /b
        if not exist 5.15.2\msvc2019\bin\qmake.exe aqt install-qt windows desktop 5.15.2 win32_msvc2019
        if not exist "qwt-6.2.0.zip" curl -L -o qwt-6.2.0.zip "https://altushost-swe.dl.sourceforge.net/project/qwt/qwt/6.2.0/qwt-6.2.0.zip"
        if exist qwt-6.2.0 rmdir /q /s qwt-6.2.0
        7z x -y "qwt-6.2.0.zip"
        set INCLUDE=
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        where qmake || exit /b
        where cl || exit /b
        pushd qwt-6.2.0
        qmake
        nmake
        nmake install
        popd
        7z a "qwt6.2.0-qt5.15.2-msvc2019-i686.zip" "C:\Qwt-6.2.0"
        if exist C:\Qwt-6.2.0 rmdir /q /s C:\Qwt-6.2.0
    - name: flavour qwt6.2.0 qt5.15.2 msvc2019 x86_64
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;%CD%\5.15.2\msvc2019_64\bin;%PATH%
        where aqt || exit /b
        if not exist 5.15.2\msvc2019_64\bin\qmake.exe aqt install-qt windows desktop 5.15.2 win64_msvc2019_64
        if not exist "qwt-6.2.0.zip" curl -L -o qwt-6.2.0.zip "https://altushost-swe.dl.sourceforge.net/project/qwt/qwt/6.2.0/qwt-6.2.0.zip"
        if exist qwt-6.2.0 rmdir /q /s qwt-6.2.0
        7z x -y "qwt-6.2.0.zip"
        set INCLUDE=
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        where qmake || exit /b
        where cl || exit /b
        pushd qwt-6.2.0
        qmake
        nmake
        nmake install
        popd
        7z a "qwt6.2.0-qt5.15.2-msvc2019-x86_64.zip" "C:\Qwt-6.2.0"
        if exist C:\Qwt-6.2.0 rmdir /q /s C:\Qwt-6.2.0
    - uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        artifacts: |
          qwt6.2.0-qt5.15.2-mingw8.1.0-i686.zip
          qwt6.2.0-qt5.15.2-mingw8.1.0-x86_64.zip
          qwt6.2.0-qt5.15.2-msvc2019-i686.zip
          qwt6.2.0-qt5.15.2-msvc2019-x86_64.zip
        token: ${{ secrets.GITHUB_TOKEN }}
