name: main
on:
  push:
    tags: '*'
jobs:
  main:
    runs-on: windows-2019
    steps:
    - name: install aqtinstall
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%
        where aqt || pip install aqtinstall
    - name: flavour qwt6.1.3 qt5.11.3 mingw5.3.0 i686
      shell: cmd
      run: |
        set PATH=%CD%\Tools\mingw530_32\bin;%CD%\5.11.3\mingw53_32\bin;C:\Miniconda;C:\Program Files\Git\mingw64\bin;C:\Miniconda\Scripts;C:\Program Files\7-Zip;%PATH%
        if not exist 5.11.3\mingw53_32\bin\qmake.exe aqt install-qt windows desktop 5.11.3 win32_mingw53
        if not exist Tools\mingw530_32\bin\gcc.exe aqt install-tool windows desktop tools_mingw qt.tools.win32_mingw530
        if not exist "qwt-6.1.3.zip" curl -L -o qwt-6.1.3.zip "https://cfhcable.dl.sourceforge.net/project/qwt/qwt/6.1.3/qwt-6.1.3.zip"
        if exist qwt-6.1.3 rmdir /q /s qwt-6.1.3
        7z x -y "qwt-6.1.3.zip"
        pushd qwt-6.1.3
        qmake
        mingw32-make install
        popd
        7z a "qwt6.1.3-qt5.11.3-mingw5.3.0-i686.zip" "C:\Qwt-6.1.3"
        if exist C:\Qwt-6.1.3 rmdir /q /s C:\Qwt-6.1.3
    - uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        artifacts: |
          qwt6.1.3-qt5.11.3-mingw5.3.0-i686.zip
        token: ${{ secrets.GITHUB_TOKEN }}
